// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swkhfucwtjpirbgkkpie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3a2hmdWN3dGpwaXJiZ2trcGllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzYzMjQsImV4cCI6MjA2OTY1MjMyNH0.GRCuuLtLHJL6FCIHzOqa5nM_LRCF8Iyu6VUvHgZt3rA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});